name: app

type: 'python:3.11'

web:
    locations:
        '/':
            # The public directory of the application relative to its root
            root: 'public'
            # The files to look for when serving a directory
            index: 
              - 'index.html'
            # Disable server-side scripts
            scripts: false
            allow: true
            # Set caching policy
            expires: 24h
            rules:
                \.(css|js|gif|jpe?g|png|svg)$:
                    expires: 4w

    commands:
        # Run a no-op process that uses no CPU resources since this is a static site
        start: sleep infinity
